-- OAK PROTOCOL · Canary: SEQUOIA14APRIL
-- Deployed: 27 April 2026
-- OKKA Expanded Intelligence OÜ
-- Seeds all FM types (27) and Library document types (31)

INSERT INTO maestro_vocabulary (vocab_type, name, definition, display_order) VALUES
('fm_type','Grant','Funding application with a hard external deadline. Requires Financial Gate review when co-financing applies.',1),
('fm_type','Application','Programme or accelerator to join. YC, residencies, fellowships. Freya alert on creation.',2),
('fm_type','Contract','Legal agreement to draft or sign. Auto-sets Legal Gate to To Clear. Wolf keeper.',3),
('fm_type','Publication','Zenodo upload, Substack post, academic paper, or DOI registration.',4),
('fm_type','Meeting','Named person or institution meeting. Creates Calendar event when Calendar field is set.',5),
('fm_type','Build','Product sprint or feature build for Lova. Auto-sets Product Gate to To Clear. Ventura Hep keeper.',6),
('fm_type','Content','Social post, field note, article, or any content for publishing. Creates Content Pipeline stub.',7),
('fm_type','Contact','Message or email action. A communication that needs to happen.',8),
('fm_type','Scout','Bounded investigation. Research with a deliverable and a deadline.',9),
('fm_type','Admin','Operational housekeeping. Subscriptions, registrations, renewals, logistics.',10),
('fm_type','Proposal','Formal proposal document for a client, partner, or investor.',11),
('fm_type','Decision','Sealed decision. Immutable record of a choice made. Creates Library stub automatically.',12),
('fm_type','Research/R&D','Ongoing research or R&D activity. Lives in Roots collection.',13),
('fm_type','Idea','Concept not yet formalised. No deadline. No action required.',14),
('fm_type','Reference','External reference — article, tool, resource, person — worth remembering.',15),
('fm_type','Target','Goal or milestone target. Quantified and dated.',16),
('fm_type','Milestone','Significant achievement reached. Creates Calendar event when Forest Roadmap = TRUE.',17),
('fm_type','Entry','General register entry. When nothing else fits. Use sparingly.',18),
('fm_type','Cost','Operational expense. Amount field = EUR amount.',19),
('fm_type','Tool','Software subscription or tool the organism uses.',20),
('fm_type','Narrative','Company story or cultural record. Cross-domain. DOI-able via Zenodo.',21),
('fm_type','Record','Formal legal or governance record. Creates Library stub automatically.',22),
('fm_type','Roundtable','Multi-seat organism deliberation. Creates Library stub with Entry ID.',23),
('fm_type','Seat Chronicle','Session record for a specific seat. Creates Library stub automatically.',24),
('fm_type','News','External news or organism announcement. Alert fires on day of insertion.',25),
('fm_type','Visual Identity','Brand asset — logo, colour system, typography. Frankie Branding keeper.',26),
('fm_type','Other','Does not fit any of the above types. Flag for Il Maestro to review.',27);

INSERT INTO maestro_vocabulary (vocab_type, name, definition, drive_folder, display_order) VALUES
('library_type','Chronicle','Session record. Append-only. Legal-quality narrative of what happened, what was decided, and why.','02. BY TYPE/01. CHRONICLES',1),
('library_type','First Page','A book founding identity document. Fixed and immutable. Contains seat identity, trust tier, system prompt summary, rules of engagement, canary at creation.','02. BY TYPE/03. BOOKS · First Pages',2),
('library_type','Working Document','A seat live scratchpad. One per seat. Append On = TRUE. Never seals. Current state only.','02. BY TYPE/02. WORKING DOCUMENTS',3),
('library_type','Roundtable','Full roundtable record. Multi-seat deliberation with Entry ID. Append-only until formally closed.','02. BY TYPE/04. ROUNDTABLES',4),
('library_type','Roundtable Verse','Per-seat delivery of roundtable context. One row per seat per roundtable.','02. BY TYPE/04. ROUNDTABLES',5),
('library_type','SoC','Shape of Choice observation. Records organism voice system evolution.','02. BY TYPE/02. WORKING DOCUMENTS',6),
('library_type','Legal Record','Formal legal review record. Produced when Legal Gate is cleared. Immutable.','02. BY TYPE/06. LEGAL RECORDS',7),
('library_type','Publication Record','Academic publication record. Produced when DOI Gate = Live.','02. BY TYPE/08. PUBLICATIONS · DOI',8),
('library_type','Principle','A governing rule or belief. Lives in Roots / Principles and Root Laws.','03. BY COLLECTION/01. ROOTS · Principles · R&D · IP',9),
('library_type','R&D Entry','Research finding or experiment. Lives in Roots / R&D.','03. BY COLLECTION/01. ROOTS · Principles · R&D · IP',10),
('library_type','Knowledge Piece','Structured piece of learning. Lives in Roots / R&D.','03. BY COLLECTION/01. ROOTS · Principles · R&D · IP',11),
('library_type','IP DOI Entry','Zenodo or IP registration record. Lives in Roots / IP.','03. BY COLLECTION/01. ROOTS · Principles · R&D · IP',12),
('library_type','Paper','Academic paper or publication.','02. BY TYPE/08. PUBLICATIONS · DOI',13),
('library_type','Application','Formal application document for YC, grants, programmes.','02. BY TYPE/13. PROPOSALS',14),
('library_type','Contract','Legal agreement. Lives in Legal book.','02. BY TYPE/07. CONTRACTS',15),
('library_type','Legal Definition','Defined legal term or position. Lives in Legal book.','02. BY TYPE/06. LEGAL RECORDS',16),
('library_type','Financial Ledger','Financial record or statement. Lives in Finance book.','02. BY TYPE/11. FINANCIAL RECORDS',17),
('library_type','Governance Entry','Governance decision record. Lives in Governance book.','03. BY COLLECTION/05. TRUNK · Governance',18),
('library_type','System Prompt','Agent identity document. Lives in Persistent Memory book.','02. BY TYPE/10. SYSTEM PROMPTS · Rules of Engagement',19),
('library_type','Rule of Engagement','Operational rule for a seat. Lives in Persistent Memory book.','02. BY TYPE/10. SYSTEM PROMPTS · Rules of Engagement',20),
('library_type','Agentic Architecture','Technical governance document. Lives in Persistent Memory book.','03. BY COLLECTION/06. TRUNK · Persistent Memory',21),
('library_type','Narrative','Company story or cultural record. Cross-domain. DOI-able via Zenodo.','02. BY TYPE/05. NARRATIVES',22),
('library_type','Post','Content publication. Social post, field note, article.','02. BY TYPE/12. CONTENT · Posts',23),
('library_type','Voice Definition','Frankie voice system document.','03. BY COLLECTION/07. TRUNK · Narrative',24),
('library_type','Product Bible','Product principles and vision. Lives in Ventura branch.','03. BY COLLECTION/09. BRANCH · Ventura · Product',25),
('library_type','Product Definition','Specific product specification. Lives in Ventura branch.','03. BY COLLECTION/09. BRANCH · Ventura · Product',26),
('library_type','Product Rule','Product governance rule. Lives in Ventura branch.','03. BY COLLECTION/09. BRANCH · Ventura · Product',27),
('library_type','Strategy Definition','Strategic direction document. Lives in Strategy book.','03. BY COLLECTION/02. TRUNK · Strategy',28),
('library_type','Proposal','Formal proposal document for clients, partners, investors.','02. BY TYPE/13. PROPOSALS',29),
('library_type','Presentation','Slide deck or visual presentation.','02. BY TYPE/09. PRESENTATIONS',30),
('library_type','Other','Does not fit any defined document type. Flag for Il Maestro to review.',NULL,31);
